version: "3.8"

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - database-volume:/var/lib/postgresql # mount a volume for persistent storage
  pgadmin:
    image: dpage/pgadmin4:5.0 # Pin for no good reason
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
  api:
    build: ./api/
    command: python3 manage.py runserver 0.0.0.0:${API_PORT}
    volumes:
      - type: bind
        source: ./api/django
        target: /code
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - database

volumes:
  database-volume:
  pgadmin-volume:
